# Generated by Django 3.2.10 on 2022-05-19 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='tag',
            new_name='tag_skill',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='value',
        ),
        migrations.CreateModel(
            name='Value_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=100, unique=True)),
                ('to_tag_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='main.skill')),
            ],
        ),
    ]
